INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Onion soup', 7);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Mushroom cream', 8.50);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Tomato cream', 8);


INSERT INTO RESTAURANT_TABLE (RESTAURANT_TABLE_STATE, TABLE_CAPACITY, TABLE_OCCUPANCY) VALUES ('PAID', 6, 4);
INSERT INTO RESTAURANT_TABLE (RESTAURANT_TABLE_STATE, TABLE_CAPACITY, TABLE_OCCUPANCY) VALUES ('FREE', 4, 0);
INSERT INTO RESTAURANT_TABLE (RESTAURANT_TABLE_STATE, TABLE_CAPACITY, TABLE_OCCUPANCY) VALUES ('FREE', 2, 0);
INSERT INTO RESTAURANT_TABLE (RESTAURANT_TABLE_STATE, TABLE_CAPACITY, TABLE_OCCUPANCY) VALUES ('OCCUPIED', 2, 2);
INSERT INTO RESTAURANT_TABLE (RESTAURANT_TABLE_STATE, TABLE_CAPACITY, TABLE_OCCUPANCY) VALUES ('OCCUPIED', 6, 2);
INSERT INTO RESTAURANT_TABLE (RESTAURANT_TABLE_STATE, TABLE_CAPACITY, TABLE_OCCUPANCY) VALUES ('OCCUPIED_WITH_PRODUCTS', 6, 2);
INSERT INTO RESTAURANT_TABLE (RESTAURANT_TABLE_STATE, TABLE_CAPACITY, TABLE_OCCUPANCY) VALUES ('FREE', 6, 0);



INSERT INTO PRODUCT_ON_TABLE (ID, RESTAURANT_TABLE_ID, AMOUNT, NAME, PRICE) VALUES (1, 1, 3, 'Onion soup', 7);